#import "@preview/quick-maths:0.2.0": shorthands
#import "@preview/mitex:0.2.4": *

#let dcases(..args) = math.cases(..args.pos().map(math.display)) // cases with display style

#let cnum(num) = str.from-unicode(9311 + num)  // 带圈数字

// ---------- 文本运算符 ----------
#let argmax = math.op("argmax", limits: true)
#let argmin = math.op("argmin", limits: true)
#let avg = math.op("avg", limits: true)
#let diag = math.op("diag", limits: true)
#let sign = math.op("sign", limits: true)
#let var = math.op("var", limits: true)
#let cov = math.op("cov", limits: true)
#let corr = math.op("corr", limits: true)
#let rank = math.op("rank", limits: true)

// ---------- 符号缩写 ----------
#let shorthand = shorthands.with(
  ($+-$, $plus.minus$),
  ($|-$, math.tack),
  ($=<$, $<=$),                // =< becomes '≤'
  ($<=$, math.arrow.l.double), // Replaces '≤'，似乎需要某一边有东西才能正常工作，原因未知
  ($~$, $#h(0.44em)$),  // two med's width
  ($!$, $#h(-0.44em)$)  // inverse of '~'
)

// ---------- 文本缩写和杂项 ----------
#let Or = $slash.big$ // 'or' as union, use 'Or' for big slash instead
#let le = $<=$
#let ge = $>=$
#let oPi = $Pi$     // backup original Pi as 'oPi'
#let Pi = $product$ // big pi as product
#let infty = $infinity$
#let int = $integral$
#let wave = $tilde$ // alternative to '~'       // $wave$, $prop$, $approx$
#let na = $nabla$
#let di = $dif$
#let pa = $diff$ // partial
#let ii = $i i$
#let ij = $i j$
#let ik = $i k$
#let ji = $j i$
#let jj = $j j$
#let jk = $j k$
#let ki = $k i$
#let kj = $k j$
#let kk = $k k$
#let xy = $x y$
#let xz = $x z$
#let yz = $y z$
#let xyz = $x y z$
#let sumi = $sum_i$
#let sumij = $sum_(i j)$
#let sumin = $sum_(i=1)^n$
#let sumim = $sum_(i=1)^m$
#let sumiN = $sum_(i=1)^N$
#let sumiM = $sum_(i=1)^M$
#let sumiK = $sum_(i=1)^K$
#let sumjn = $sum_(j=1)^n$
#let sumjm = $sum_(j=1)^m$
#let sumjN = $sum_(j=1)^N$
#let sumjM = $sum_(j=1)^M$
#let sumkK = $sum_(k=1)^K$
#let summM = $sum_(m=1)^M$
#let sumnN = $sum_(n=1)^N$
#let sumtT = $sum_(t=1)^T$
#let Pii = $product_i$
#let Pij = $product_(i j)$
#let Piin = $product_(i=1)^n$
#let Pijn = $product_(j=1)^n$
#let PiiN = $product_(i=1)^N$
#let PijN = $product_(j=1)^N$
#let PikK = $product_(k=1)^K$
#let PimM = $product_(m=1)^M$
#let PinN = $product_(n=1)^N$
#let PitT = $product_(t=1)^T$
#let first = $1^"st"$
#let second = $2^"nd"$
#let third = $3^"rd"$
// AI specific
#let MLP = math.text("MLP")
#let CNN = math.text("CNN")
#let RNN = math.text("RNN")
#let Transformer = math.text("Transformer")
#let Attention = math.text("Attention")
#let clamp = math.text("clamp")

// ---------- 常用单位（这样它们就可以直接囊括入 $$） ----------
#let bit = math.text("bit")
#let bits = math.text("bits")
#let byte = math.text("byte")
#let bytes = math.text("bytes")
#let kb = math.text("KB")
#let KB = math.text("KB")
#let KiB = math.text("KiB")
#let mb = math.text("MB")
#let MB = math.text("MB")
#let MiB = math.text("MiB")
#let gb = math.text("GB")
#let GB = math.text("GB")
#let GiB = math.text("GiB")
#let tb = math.text("TB")
#let TB = math.text("TB")
#let TiB = math.text("TiB")
#let pb = math.text("PB")
#let PB = math.text("PB")
#let PiB = math.text("PiB")
#let eb = math.text("EB")
#let EB = math.text("EB")
#let EiB = math.text("EiB")
#let fps = math.text("fps")
#let FPS = math.text("FPS")
#let ms = math.text("ms")
#let sec = math.text("sec")
// #let min = math.text("min") // 'min' used for min op
#let wk = math.text("wk")
#let mo = math.text("mo")
#let yr = math.text("yr")
#let Hz = math.text("Hz")
#let GHz = math.text("GHz")
#let mm = math.text("mm")
#let cm = math.text("cm")
#let dm = math.text("dm")
#let km = math.text("km")

// ---------- 防铸币操作与常用简写 ----------
#let dx = $dif x$
#let exist = $exists$
#let st = $#h(0.44em)s.t.#h(0.44em)$ // such that
#let is = math.text("is")
#let iff = math.bold("iff")

// ---------- 希腊字母 (siplified to 2 letters) ----------
#let rh  = $rho$
#let rh0 = $rho_0$
#let rh1 = $rho_1$
#let rh2 = $rho_2$
#let rhi = $rho_i$
#let rhj = $rho_j$
#let rhk = $rho_k$
#let rhm = $rho_m$
#let rhM = $rho_M$
#let rhn = $rho_n$
#let rhN = $rho_N$
#let si  = $sigma$
#let si0 = $sigma_0$
#let si1 = $sigma_1$
#let si2 = $sigma_2$
#let sii = $sigma_i$
#let sij = $sigma_j$
#let sik = $sigma_k$
#let sim = $sigma_m$
#let siM = $sigma_M$
// #let sin = $sigma_n$ // 'sin' is a keyword
#let siN = $sigma_N$
#let Si  = $Sigma$
#let Si0 = $Sigma_0$
#let Si1 = $Sigma_1$
#let Si2 = $Sigma_2$
#let Sii = $Sigma_i$
#let Sij = $Sigma_j$
#let Sik = $Sigma_k$
#let Sim = $Sigma_m$
#let SiM = $Sigma_M$
#let Sin = $Sigma_n$ // 'Sin' is a keyword
#let SiN = $Sigma_N$
#let de  = $delta$
#let de0 = $delta_0$
#let de1 = $delta_1$
#let de2 = $delta_2$
#let dei = $delta_i$
#let dej = $delta_j$
#let dek = $delta_k$
#let dem = $delta_m$
#let deM = $delta_M$
#let den = $delta_n$
#let deN = $delta_N$
#let De  = $Delta$
#let De0 = $Delta_0$
#let De1 = $Delta_1$
#let De2 = $Delta_2$
#let Dei = $Delta_i$
#let Dej = $Delta_j$
#let Dek = $Delta_k$
#let Dem = $Delta_m$
#let DeM = $Delta_M$
#let Den = $Delta_n$
#let DeN = $Delta_N$
#let al  = $alpha$
#let al0 = $alpha_0$
#let al1 = $alpha_1$
#let al2 = $alpha_2$
#let ali = $alpha_i$
#let alj = $alpha_j$
#let alk = $alpha_k$
#let alm = $alpha_m$
#let alM = $alpha_M$
#let aln = $alpha_n$
#let alN = $alpha_N$
#let be  = $beta$
#let be0 = $beta_0$
#let be1 = $beta_1$
#let be2 = $beta_2$
#let bei = $beta_i$
#let bej = $beta_j$
#let bek = $beta_k$
#let bem = $beta_m$
#let beM = $beta_M$
#let ben = $beta_n$
#let beN = $beta_N$
#let ta  = $tau$
#let ta0 = $tau_0$
#let ta1 = $tau_1$
#let ta2 = $tau_2$
#let tai = $tau_i$
#let taj = $tau_j$
#let tak = $tau_k$
#let tam = $tau_m$
#let taM = $tau_M$
// #let tan = $tau_n$ // 'tan' is a keyword
#let taN = $tau_N$
#let Ta  = $Tau$
#let Ta0 = $Tau_0$
#let Ta1 = $Tau_1$
#let Ta2 = $Tau_2$
#let Tai = $Tau_i$
#let Taj = $Tau_j$
#let Tak = $Tau_k$
#let Tam = $Tau_m$
#let TaM = $Tau_M$
#let Tan = $Tau_n$
#let TaN = $Tau_N$
#let th = $theta$
#let th0 = $theta_0$
#let th1 = $theta_1$
#let th2 = $theta_2$
#let thi = $theta_i$
#let thj = $theta_j$
#let thk = $theta_k$
#let thm = $theta_m$
#let thM = $theta_M$
#let thn = $theta_n$
#let thN = $theta_N$
#let Th = $Theta$
#let Th0 = $Theta_0$
#let Th1 = $Theta_1$
#let Th2 = $Theta_2$
#let Thi = $Theta_i$
#let Thj = $Theta_j$
#let Thk = $Theta_k$
#let Thm = $Theta_m$
#let ThM = $Theta_M$
#let Thn = $Theta_n$
#let ThN = $Theta_N$
#let ep = $epsilon$
#let ep0 = $epsilon_0$
#let ep1 = $epsilon_1$
#let ep2 = $epsilon_2$
#let epi = $epsilon_i$
#let epj = $epsilon_j$
#let epk = $epsilon_k$
#let epm = $epsilon_m$
#let epM = $epsilon_M$
#let epn = $epsilon_n$
#let epN = $epsilon_N$
#let ga = $gamma$
#let ga0 = $gamma_0$
#let ga1 = $gamma_1$
#let ga2 = $gamma_2$
#let gai = $gamma_i$
#let gaj = $gamma_j$
#let gak = $gamma_k$
#let gam = $gamma_m$
#let gaM = $gamma_M$
#let gan = $gamma_n$
#let gaN = $gamma_N$
#let Ga = $Gamma$
#let Ga0 = $Gamma_0$
#let Ga1 = $Gamma_1$
#let Ga2 = $Gamma_2$
#let Gai = $Gamma_i$
#let Gaj = $Gamma_j$
#let Gak = $Gamma_k$
#let Gam = $Gamma_m$
#let GaM = $Gamma_M$
#let Gan = $Gamma_n$
#let GaN = $Gamma_N$
#let la  = $lambda$
#let la0 = $lambda_0$
#let la1 = $lambda_1$
#let la2 = $lambda_2$
#let lai = $lambda_i$
#let laj = $lambda_j$
#let lak = $lambda_k$
#let lam = $lambda_m$
#let laM = $lambda_M$
#let lan = $lambda_n$
#let laN = $lambda_N$
#let La  = $Lambda$
#let La0 = $Lambda_0$
#let La1 = $Lambda_1$
#let La2 = $Lambda_2$
#let Lai = $Lambda_i$
#let Laj = $Lambda_j$
#let Lak = $Lambda_k$
#let Lam = $Lambda_m$
#let LaM = $Lambda_M$
#let Lan = $Lambda_n$
#let LaN = $Lambda_N$
#let om  = $omega$
#let om0 = $omega_0$
#let om1 = $omega_1$
#let om2 = $omega_2$
#let omi = $omega_i$
#let omj = $omega_j$
#let omk = $omega_k$
#let omm = $omega_m$
#let omM = $omega_M$
#let omn = $omega_n$
#let omN = $omega_N$
#let Om  = $Omega$
#let Om0 = $Omega_0$
#let Om1 = $Omega_1$
#let Om2 = $Omega_2$
#let Omi = $Omega_i$
#let Omj = $Omega_j$
#let Omk = $Omega_k$
#let Omm = $Omega_m$
#let OmM = $Omega_M$
#let Omn = $Omega_n$
#let OmN = $Omega_N$
#let pi0 = $pi_0$
#let pi1 = $pi_1$
#let pi2 = $pi_2$
#let pii = $pi_i$
#let pij = $pi_j$
#let pik = $pi_k$
#let pim = $pi_m$
#let piM = $pi_M$
// #let pin = $pi_n$ // 'pin' is a keyword for pinit package
#let piN = $pi_N$

// ---------- bold, cal, hat, tilde, arrow, overline letters ----------
// bold letters
#let ba = math.bold("a")
#let bb = math.bold("b")
#let bc = math.bold("c")
#let bd = math.bold("d")
// #let be = math.bold("e") // 'be' used for beta
#let bf = math.bold("f")
#let bg = math.bold("g")
#let bh = math.bold("h")
// #let bi = math.bold("i")
// #let bj = math.bold("j")
// #let bk = math.bold("k") // used for b_i b_j b_k
#let bm = math.bold("m")
#let bn = math.bold("n")
#let bo = math.bold("o")
#let bp = math.bold("p")
#let bq = math.bold("q")
#let br = math.bold("r")
#let bs = math.bold("s")
#let bt = math.bold("t")
#let bu = math.bold("u")
#let bv = math.bold("v")
#let bw = math.bold("w")
#let bx = math.bold("x")
#let by = math.bold("y")
#let bz = math.bold("z")
#let bA = math.bold("A")
#let bB = math.bold("B")
#let bC = math.bold("C")
#let bE = math.bold("E")
#let bF = math.bold("F")
#let bG = math.bold("G")
#let bH = math.bold("H")
#let bI = math.bold("I")
#let bJ = math.bold("J")
#let bK = math.bold("K")
#let bL = math.bold("L")
#let bM = math.bold("M")
#let bN = math.bold("N")
#let bP = math.bold("P")
#let bS = math.bold("S")
#let bT = math.bold("T")
#let bU = math.bold("U")
#let bV = math.bold("V")
#let bW = math.bold("W")
#let bX = math.bold("X")
#let bY = math.bold("Y")
#let bZ = math.bold("Z")
#let bxi = math.bold($xi$)
#let bpi = math.bold($pi$)
#let bth = math.bold($theta$)
#let bmu = math.bold($mu$)
// cal letters (only uppercases)
#let cA = math.cal("A")
#let cB = math.cal("B")
#let cC = math.cal("C")
#let cD = math.cal("D")
#let cF = math.cal("F")
#let cG = math.cal("G")
#let cH = math.cal("H")
#let cJ = math.cal("J")
#let cL = math.cal("L")
#let cM = math.cal("M")
#let cN = math.cal("N")
#let cP = math.cal("P")
#let cS = math.cal("S")
#let cV = math.cal("V")
#let cW = math.cal("W")
#let cX = math.cal("X")
// letters with hat
#let ha = math.hat("a")
#let hb = math.hat("b")
#let hc = math.hat("c")
#let hd = math.hat("d")
#let he = math.hat("e")
#let hf = math.hat("f")
#let hg = math.hat("g")
#let hh = math.hat("h")
// #let hi = math.hat("i")
// #let hj = math.hat("j")
// #let hk = math.hat("k") // used for h_i h_j h_k
#let hm = math.hat("m")
#let hn = math.hat("n")
#let hs = math.hat("s")
#let ht = math.hat("t")
#let hu = math.hat("u")
#let hv = math.hat("v")
#let hw = math.hat("w")
#let hx = math.hat("x")
#let hy = math.hat("y")
#let hz = math.hat("z")
#let hA = math.hat("A")
#let hB = math.hat("B")
#let hC = math.hat("C")
#let hD = math.hat("D")
#let hE = math.hat("E")
#let hF = math.hat("F")
#let hG = math.hat("G")
#let hH = math.hat("H")
#let hI = math.hat("I")
#let hJ = math.hat("J")
#let hK = math.hat("K")
#let hL = math.hat("L")
#let hM = math.hat("M")
#let hN = math.hat("N")
#let hO = math.hat("O")
#let hP = math.hat("P")
#let hQ = math.hat("Q")
#let hS = math.hat("S")
#let hT = math.hat("T")
#let hU = math.hat("U")
#let hV = math.hat("V")
#let hW = math.hat("W")
#let hX = math.hat("X")
#let hY = math.hat("Y")
#let hZ = math.hat("Z")
// letters with tilde
// #let ta = math.tilde("a") // 'ta' used for tau
#let tb = math.tilde("b")
#let tc = math.tilde("c")
#let td = math.tilde("d")
#let te = math.tilde("e")
#let tf = math.tilde("f")
#let tg = math.tilde("g")
// #let th = math.tilde("h") // 'th' used for theta
// #let ti = math.tilde("i")
// #let tj = math.tilde("j")
// #let tk = math.tilde("k") // used for t_i t_j t_k
#let tm = math.tilde("m")
#let tn = math.tilde("n")
#let to = math.tilde("o")
#let tp = math.tilde("p")
#let tq = math.tilde("q")
#let ts = math.tilde("s")
#let tt = math.tilde("t")
#let tu = math.tilde("u")
#let tv = math.tilde("v")
#let tw = math.tilde("w")
#let tx = math.tilde("x")
#let ty = math.tilde("y")
#let tz = math.tilde("z")
#let tA = math.tilde("A")
#let tB = math.tilde("B")
#let tC = math.tilde("C")
#let tD = math.tilde("D")
#let tE = math.tilde("E")
#let tF = math.tilde("F")
#let tG = math.tilde("G")
#let tH = math.tilde("H")
#let tI = math.tilde("I")
#let tJ = math.tilde("J")
#let tH = math.tilde("H")
#let tI = math.tilde("I")
#let tJ = math.tilde("J")
#let tK = math.tilde("K")
#let tM = math.tilde("M")
#let tN = math.tilde("N")
#let tO = math.tilde("O")
#let tP = math.tilde("P")
#let tQ = math.tilde("Q")
#let tS = math.tilde("S")
#let tT = math.tilde("T")
#let tU = math.tilde("U")
#let tV = math.tilde("V")
#let tW = math.tilde("W")
#let tX = math.tilde("X")
#let tY = math.tilde("Y")
#let tZ = math.tilde("Z")
// letters with arrow
#let aa = math.arrow("a")
#let ab = math.arrow("b")
#let ac = math.arrow("c")
#let ad = math.arrow("d")
#let ae = math.arrow("e")
#let af = math.arrow("f")
#let ag = math.arrow("g")
#let ah = math.arrow("h")
// #let ai = math.arrow("i")
// #let aj = math.arrow("j")
// #let ak = math.arrow("k") // used for a_i a_j a_k
// #let as = math.arrow("s") // 'as' is a keyword
#let at = math.arrow("t")
#let au = math.arrow("u")
#let av = math.arrow("v")
#let aw = math.arrow("w")
#let ax = math.arrow("x")
#let ay = math.arrow("y")
#let az = math.arrow("z")
#let aA = math.arrow("A")
#let aB = math.arrow("B")
#let aC = math.arrow("C")
#let aD = math.arrow("D")
#let aE = math.arrow("E")
#let aF = math.arrow("F")
#let aG = math.arrow("G")
#let aH = math.arrow("H")
#let aI = math.arrow("I")
#let aJ = math.arrow("J")
#let aK = math.arrow("K")
#let aS = math.arrow("S")
#let aT = math.arrow("T")
#let aU = math.arrow("U")
#let aV = math.arrow("V")
#let aW = math.arrow("W")
#let aX = math.arrow("X")
#let aY = math.arrow("Y")
#let aZ = math.arrow("Z")
// overline letters
#let oa = math.macron("a") // or overline (slightly too long I think)
#let ob = math.macron("b")
#let oc = math.macron("c")
#let od = math.macron("d")
#let oe = math.macron("e")
#let of = math.macron("f")
#let og = math.macron("g")
#let oh = math.macron("h")
#let oi = math.macron("i")
#let oj = math.macron("j")
#let ok = math.macron("k")
// #let om = math.macron("m") // 'om' used for omega
#let on = math.macron("n")
#let os = math.macron("s")
#let ot = math.macron("t")
#let ou = math.macron("u")
#let ov = math.macron("v")
#let ow = math.macron("w")
#let ox = math.macron("x")
#let oy = math.macron("y")
#let oz = math.macron("z")
#let oA = math.macron("A")
#let oB = math.macron("B")
#let oC = math.macron("C")
#let oD = math.macron("D")
#let oE = math.macron("E")
#let oF = math.macron("F")
#let oG = math.macron("G")
#let oH = math.macron("H")
#let oI = math.macron("I")
#let oJ = math.macron("J")
#let oK = math.macron("K")
// #let oM = math.macron("M") // 'oM' used for cal
#let oN = math.macron("N")
#let oP = math.macron("P")
#let oQ = math.macron("Q")
#let oS = math.macron("S")
#let oT = math.macron("T")
#let oU = math.macron("U")
#let oV = math.macron("V")
#let oW = math.macron("W")
#let oX = math.macron("X")
#let oY = math.macron("Y")
#let oZ = math.macron("Z")

// ---------- subscripts for common letters ----------
#let x0 = $x_0$
#let x1 = $x_1$
#let x2 = $x_2$
// #let xi = $x_i$ // 'xi' used for xi
#let xj = $x_j$
#let xk = $x_k$
#let xm = $x_m$
#let xM = $x_M$
#let xn = $x_n$
#let xN = $x_N$
#let y0 = $y_0$
#let y1 = $y_1$
#let y2 = $y_2$
#let yi = $y_i$
#let yj = $y_j$
#let yk = $y_k$
#let ym = $y_m$
#let yM = $y_M$
#let yn = $y_n$
#let yN = $y_N$
#let z0 = $z_0$
#let z1 = $z_1$
#let z2 = $z_2$
#let zi = $z_i$
#let zj = $z_j$
#let zk = $z_k$
#let zm = $z_m$
#let zM = $z_M$
#let zn = $z_n$
#let zN = $z_N$
#let s0 = $s_0$
#let s1 = $s_1$
#let s2 = $s_2$
// #let si = $s_i$ // 'si' used for sigma
#let sj = $s_j$
#let sk = $s_k$
#let sm = $s_m$
#let sM = $s_M$
#let sn = $s_n$
#let sN = $s_N$
#let t0 = $t_0$
#let t1 = $t_1$
#let t2 = $t_2$
#let ti = $t_i$
#let tj = $t_j$
#let tk = $t_k$
// #let tm = $t_m$
// #let tM = $t_M$
// #let tn = $t_n$
// #let tN = $t_N$ // 't' used for tilde
#let u0 = $u_0$
#let u1 = $u_1$
#let u2 = $u_2$
#let ui = $u_i$
#let uj = $u_j$
#let uk = $u_k$
#let um = $u_m$
#let uM = $u_M$
#let un = $u_n$
#let uN = $u_N$
#let v0 = $v_0$
#let v1 = $v_1$
#let v2 = $v_2$
#let vi = $v_i$
#let vj = $v_j$
#let vk = $v_k$
#let vm = $v_m$
#let vM = $v_M$
#let vn = $v_n$
#let vN = $v_N$
#let w0 = $w_0$
#let w1 = $w_1$
#let w2 = $w_2$
#let wi = $w_i$
#let wj = $w_j$
#let wk = $w_k$
#let wm = $w_m$
#let wM = $w_M$
#let wn = $w_n$
#let wN = $w_N$
#let a0 = $a_0$
#let a1 = $a_1$
#let a2 = $a_2$
#let ai = $a_i$
#let aj = $a_j$
#let ak = $a_k$
// #let am = $a_m$
// #let aM = $a_M$
// #let an = $a_n$
// #let aN = $a_N$ // 'a' used for arrow
#let b0 = $b_0$
#let b1 = $b_1$
#let b2 = $b_2$
#let bi = $b_i$
#let bj = $b_j$
#let bk = $b_k$
// #let bm = $b_m$
// #let bM = $b_M$
// #let bn = $b_n$
// #let bN = $b_N$ // 'b' used for bold
#let c0 = $c_0$
#let c1 = $c_1$
#let c2 = $c_2$
#let ci = $c_i$
#let cj = $c_j$
#let ck = $c_k$
// #let cm = $c_m$ // 'cm' used as a unit
// #let cM = $c_M$ // 'cM' used for cal
#let cn = $c_n$
// #let cN = $c_N$ // 'cN' used for cal
#let d0 = $d_0$
#let d1 = $d_1$
#let d2 = $d_2$
#let di = $d_i$
#let dj = $d_j$
#let dk = $d_k$
#let dm = $d_m$
#let dM = $d_M$
#let dn = $d_n$
#let dN = $d_N$
#let e0 = $e_0$
#let e1 = $e_1$
#let e2 = $e_2$
#let ei = $e_i$
#let ej = $e_j$
#let ek = $e_k$
#let em = $e_m$
#let eM = $e_M$
#let en = $e_n$
#let eN = $e_N$
#let f0 = $f_0$
#let f1 = $f_1$
#let f2 = $f_2$
#let fi = $f_i$
#let fj = $f_j$
#let fk = $f_k$
#let fm = $f_m$
#let fM = $f_M$
#let fn = $f_n$
#let fN = $f_N$
#let g0 = $g_0$
#let g1 = $g_1$
#let g2 = $g_2$
#let gi = $g_i$
#let gj = $g_j$
#let gk = $g_k$
#let gm = $g_m$
#let gM = $g_M$
#let gn = $g_n$
#let gN = $g_N$
#let h0 = $h_0$
#let h1 = $h_1$
#let h2 = $h_2$
#let hi = $h_i$
#let hj = $h_j$
#let hk = $h_k$
// #let hm = $h_m$
// #let hM = $h_M$
// #let hn = $h_n$
// #let hN = $h_N$ // 'h' used for hat
#let i0 = $i_0$
#let i1 = $i_1$
#let i2 = $i_2$
// #let ii = $i_i$ 'ii' used for i i with backspace between
// #let ij = $i_j$ 'ij' used for i j with backspace between
// #let ik = $i_k$ // 'ik' used for i k with backspace between
#let im = $i_m$
#let iM = $i_M$
// #let in = $i_n$ // 'in' is a keyword
#let iN = $i_N$
#let j0 = $j_0$
#let j1 = $j_1$
#let j2 = $j_2$
// #let ji = $j_i$ // 'ji' used for j i with backspace between
// #let jj = $j_j$ // 'jj' used for j j with backspace between
// #let jk = $j_k$ // 'jk' used for j k with backspace between
#let jm = $j_m$
#let jM = $j_M$
#let jn = $j_n$
#let jN = $j_N$
#let k0 = $k_0$
#let k1 = $k_1$
#let k2 = $k_2$
// #let ki = $k_i$ // 'ki' used for k i with backspace between
// #let kj = $k_j$ // 'kj' used for k j with backspace between
// #let kk = $k_k$ // 'kk' used for k k with backspace between
#let km = $k_m$
#let kM = $k_M$
#let kn = $k_n$
#let kN = $k_N$
