#import "@preview/quick-maths:0.2.0": shorthands
#import "@preview/mitex:0.2.5": *

#let dcases(..args) = math.cases(..args.pos().map(math.display)) // cases with display style

#let cnum(num) = str.from-unicode(9311 + num)  // 带圈数字

// ---------- 文本运算符 ----------
#let argmax = math.op("argmax", limits: true)
#let argmin = math.op("argmin", limits: true)
#let avg = math.op("avg", limits: true)
#let diag = math.op("diag", limits: true)
#let sign = math.op("sign", limits: true)
#let var = math.op("var", limits: true)
#let cov = math.op("cov", limits: true)
#let corr = math.op("corr", limits: true)
#let rank = math.op("rank", limits: true)

// ---------- 符号缩写 ----------
#let shorthand = shorthands.with(
  ($+-$, $plus.minus$),
  ($|-$, math.tack),
  ($=<$, $<=$),                // =< becomes '≤'
  ($<=$, math.arrow.l.double), // Replaces '≤'，似乎需要某一边有东西才能正常工作，原因未知
  ($~~$, $#h(0.5em)$),  // two med's width
  ($!!$, $#h(-0.5em)$)  // inverse of '~'
)

// ---------- 文本缩写和杂项 ----------
#let Or = $slash.big$ // 'or' as union, use 'Or' for big slash instead
#let le = $<=$
#let ge = $>=$
#let oPi = $Pi$     // backup original Pi as 'oPi'
#let Pi = $product$ // big pi as product
#let infty = $infinity$
#let int = $integral$
#let wave = $~$   // alternative to '~'
#let fact = $"!"$ // alternative to '!'
#let na = $nabla$
#let di = $dif$
#let pa = $diff$ // partial
#let ii = $i i$
#let ij = $i j$
#let ik = $i k$
#let ji = $j i$
#let jj = $j j$
#let jk = $j k$
#let ki = $k i$
#let kj = $k j$
#let kk = $k k$
#let xy = $x y$
#let xz = $x z$
#let yz = $y z$
#let xyz = $x y z$
#let sumi = $sum_i$
#let sumij = $sum_(i j)$
#let sumin = $sum_(i=1)^n$
#let sumim = $sum_(i=1)^m$
#let sumiN = $sum_(i=1)^N$
#let sumiM = $sum_(i=1)^M$
#let sumiK = $sum_(i=1)^K$
#let sumjn = $sum_(j=1)^n$
#let sumjm = $sum_(j=1)^m$
#let sumjN = $sum_(j=1)^N$
#let sumjM = $sum_(j=1)^M$
#let sumkK = $sum_(k=1)^K$
#let summM = $sum_(m=1)^M$
#let sumnN = $sum_(n=1)^N$
#let sumtT = $sum_(t=1)^T$
#let Pii = $product_i$
#let Pij = $product_(i j)$
#let Piin = $product_(i=1)^n$
#let Pijn = $product_(j=1)^n$
#let PiiN = $product_(i=1)^N$
#let PijN = $product_(j=1)^N$
#let PikK = $product_(k=1)^K$
#let PimM = $product_(m=1)^M$
#let PinN = $product_(n=1)^N$
#let PitT = $product_(t=1)^T$
#let first = $1^"st"$
#let second = $2^"nd"$
#let third = $3^"rd"$

// AI specific
#let MLP = math.text("MLP")
#let FFN = math.text("FFN")
#let CNN = math.text("CNN")
#let RNN = math.text("RNN")
#let Transformer = math.text("Transformer")
#let Attention = math.text("Attention")
#let clamp = math.text("clamp")
#let token = math.text("token")
#let softmax = math.text("softmax")
#let Concat = math.text("Concat")
#let MultiHead = math.text("MultiHead")
#let Attention = math.text("Attention")
#let SelfAttention = math.text("SelfAttention")
#let CrossAttention = math.text("CrossAttention")
#let Diffusion = math.text("Diffusion")
#let MSE = math.text("MSE")
#let KL = math.text("KL")

// ---------- 常用单位（这样它们就可以直接囊括入 $$） ----------
#let bit = math.text("bit")
#let bits = math.text("bits")
#let byte = math.text("byte")
#let bytes = math.text("bytes")
#let kb = math.text("KB")
#let KB = math.text("KB")
#let KiB = math.text("KiB")
#let mb = math.text("MB")
#let MB = math.text("MB")
#let MiB = math.text("MiB")
#let gb = math.text("GB")
#let GB = math.text("GB")
#let GiB = math.text("GiB")
#let tb = math.text("TB")
#let TB = math.text("TB")
#let TiB = math.text("TiB")
#let pb = math.text("PB")
#let PB = math.text("PB")
#let PiB = math.text("PiB")
#let eb = math.text("EB")
#let EB = math.text("EB")
#let EiB = math.text("EiB")
#let fps = math.text("fps")
#let FPS = math.text("FPS")
#let ms = math.text("ms")
#let sec = math.text("sec")
// #let min = math.text("min") // 'min' used for min op
#let wk = math.text("wk")
#let mo = math.text("mo")
#let yr = math.text("yr")
#let Hz = math.text("Hz")
#let GHz = math.text("GHz")
#let mm = math.text("mm")
#let cm = math.text("cm")
#let dm = math.text("dm")
#let km = math.text("km")

// ---------- 防铸币操作与常用简写 ----------
#let dx = $dif x$
#let exist = $exists$
#let st = $#h(0.44em)s.t.#h(0.44em)$ // such that
#let iff = math.bold("iff")

// ---------- 希腊字母 (siplified to 2 letters) ----------
#let rh  = $rho$
#let rh0 = $rho_0$
#let rh1 = $rho_1$
#let rh2 = $rho_2$
#let rhi = $rho_i$
#let rhj = $rho_j$
#let rhk = $rho_k$
#let rhm = $rho_m$
#let rhM = $rho_M$
#let rhn = $rho_n$
#let rhN = $rho_N$
#let si  = $sigma$
#let si0 = $sigma_0$
#let si1 = $sigma_1$
#let si2 = $sigma_2$
#let sii = $sigma_i$
#let sij = $sigma_j$
#let sik = $sigma_k$
#let sim = $sigma_m$
#let siM = $sigma_M$
// #let sin = $sigma_n$ // 'sin' is a keyword
#let siN = $sigma_N$
#let Si  = $Sigma$
#let Si0 = $Sigma_0$
#let Si1 = $Sigma_1$
#let Si2 = $Sigma_2$
#let Sii = $Sigma_i$
#let Sij = $Sigma_j$
#let Sik = $Sigma_k$
#let Sim = $Sigma_m$
#let SiM = $Sigma_M$
#let Sin = $Sigma_n$ // 'Sin' is a keyword
#let SiN = $Sigma_N$
#let de  = $delta$
#let de0 = $delta_0$
#let de1 = $delta_1$
#let de2 = $delta_2$
#let dei = $delta_i$
#let dej = $delta_j$
#let dek = $delta_k$
#let dem = $delta_m$
#let deM = $delta_M$
#let den = $delta_n$
#let deN = $delta_N$
#let De  = $Delta$
#let De0 = $Delta_0$
#let De1 = $Delta_1$
#let De2 = $Delta_2$
#let Dei = $Delta_i$
#let Dej = $Delta_j$
#let Dek = $Delta_k$
#let Dem = $Delta_m$
#let DeM = $Delta_M$
#let Den = $Delta_n$
#let DeN = $Delta_N$
#let al  = $alpha$
#let al0 = $alpha_0$
#let al1 = $alpha_1$
#let al2 = $alpha_2$
#let ali = $alpha_i$
#let alj = $alpha_j$
#let alk = $alpha_k$
#let alm = $alpha_m$
#let alM = $alpha_M$
#let aln = $alpha_n$
#let alN = $alpha_N$
#let be  = $beta$
#let be0 = $beta_0$
#let be1 = $beta_1$
#let be2 = $beta_2$
#let bei = $beta_i$
#let bej = $beta_j$
#let bek = $beta_k$
#let bem = $beta_m$
#let beM = $beta_M$
#let ben = $beta_n$
#let beN = $beta_N$
#let ta  = $tau$
#let ta0 = $tau_0$
#let ta1 = $tau_1$
#let ta2 = $tau_2$
#let tai = $tau_i$
#let taj = $tau_j$
#let tak = $tau_k$
#let tam = $tau_m$
#let taM = $tau_M$
// #let tan = $tau_n$ // 'tan' is a keyword
#let taN = $tau_N$
#let Ta  = $Tau$
#let Ta0 = $Tau_0$
#let Ta1 = $Tau_1$
#let Ta2 = $Tau_2$
#let Tai = $Tau_i$
#let Taj = $Tau_j$
#let Tak = $Tau_k$
#let Tam = $Tau_m$
#let TaM = $Tau_M$
#let Tan = $Tau_n$
#let TaN = $Tau_N$
#let th = $theta$
#let th0 = $theta_0$
#let th1 = $theta_1$
#let th2 = $theta_2$
#let thi = $theta_i$
#let thj = $theta_j$
#let thk = $theta_k$
#let thm = $theta_m$
#let thM = $theta_M$
#let thn = $theta_n$
#let thN = $theta_N$
#let Th = $Theta$
#let Th0 = $Theta_0$
#let Th1 = $Theta_1$
#let Th2 = $Theta_2$
#let Thi = $Theta_i$
#let Thj = $Theta_j$
#let Thk = $Theta_k$
#let Thm = $Theta_m$
#let ThM = $Theta_M$
#let Thn = $Theta_n$
#let ThN = $Theta_N$
#let ep = $epsilon$
#let ep0 = $epsilon_0$
#let ep1 = $epsilon_1$
#let ep2 = $epsilon_2$
#let epi = $epsilon_i$
#let epj = $epsilon_j$
#let epk = $epsilon_k$
#let epm = $epsilon_m$
#let epM = $epsilon_M$
#let epn = $epsilon_n$
#let epN = $epsilon_N$
#let ga = $gamma$
#let ga0 = $gamma_0$
#let ga1 = $gamma_1$
#let ga2 = $gamma_2$
#let gai = $gamma_i$
#let gaj = $gamma_j$
#let gak = $gamma_k$
#let gam = $gamma_m$
#let gaM = $gamma_M$
#let gan = $gamma_n$
#let gaN = $gamma_N$
#let Ga = $Gamma$
#let Ga0 = $Gamma_0$
#let Ga1 = $Gamma_1$
#let Ga2 = $Gamma_2$
#let Gai = $Gamma_i$
#let Gaj = $Gamma_j$
#let Gak = $Gamma_k$
#let Gam = $Gamma_m$
#let GaM = $Gamma_M$
#let Gan = $Gamma_n$
#let GaN = $Gamma_N$
#let la  = $lambda$
#let la0 = $lambda_0$
#let la1 = $lambda_1$
#let la2 = $lambda_2$
#let lai = $lambda_i$
#let laj = $lambda_j$
#let lak = $lambda_k$
#let lam = $lambda_m$
#let laM = $lambda_M$
#let lan = $lambda_n$
#let laN = $lambda_N$
#let La  = $Lambda$
#let La0 = $Lambda_0$
#let La1 = $Lambda_1$
#let La2 = $Lambda_2$
#let Lai = $Lambda_i$
#let Laj = $Lambda_j$
#let Lak = $Lambda_k$
#let Lam = $Lambda_m$
#let LaM = $Lambda_M$
#let Lan = $Lambda_n$
#let LaN = $Lambda_N$
#let om  = $omega$
#let om0 = $omega_0$
#let om1 = $omega_1$
#let om2 = $omega_2$
#let omi = $omega_i$
#let omj = $omega_j$
#let omk = $omega_k$
#let omm = $omega_m$
#let omM = $omega_M$
#let omn = $omega_n$
#let omN = $omega_N$
#let Om  = $Omega$
#let Om0 = $Omega_0$
#let Om1 = $Omega_1$
#let Om2 = $Omega_2$
#let Omi = $Omega_i$
#let Omj = $Omega_j$
#let Omk = $Omega_k$
#let Omm = $Omega_m$
#let OmM = $Omega_M$
#let Omn = $Omega_n$
#let OmN = $Omega_N$
#let pi0 = $pi_0$
#let pi1 = $pi_1$
#let pi2 = $pi_2$
#let pii = $pi_i$
#let pij = $pi_j$
#let pik = $pi_k$
#let pim = $pi_m$
#let piM = $pi_M$
// #let pin = $pi_n$ // 'pin' is a keyword for pinit package
#let piN = $pi_N$
#let ka = $kappa$
#let ka0 = $kappa_0$
#let ka1 = $kappa_1$
#let ka2 = $kappa_2$
#let kai = $kappa_i$
#let kaj = $kappa_j$
#let kak = $kappa_k$
#let kam = $kappa_m$
#let kaM = $kappa_M$
#let kan = $kappa_n$
#let kaN = $kappa_N$

// ---------- bold, cal, hat, tilde, arrow, overline letters ----------
// bold letters
#let ba = $bold(a)$
#let bb = $bold(b)$
#let bc = $bold(c)$
#let bd = $bold(d)$
// #let be = $bold(e)$ // 'be' used for beta
#let bf = $bold(f)$
#let bg = $bold(g)$
#let bh = $bold(h)$
// #let bi = $bold(i)$
// #let bj = $bold(j)$
// #let bk = $bold(k)$ // used for b_i b_j b_k
#let bm = $bold(m)$
#let bn = $bold(n)$
#let bo = $bold(o)$
#let bp = $bold(p)$
#let bq = $bold(q)$
#let br = $bold(r)$
#let bs = $bold(s)$
#let bt = $bold(t)$
#let bu = $bold(u)$
#let bv = $bold(v)$
#let bw = $bold(w)$
#let bx = $bold(x)$
#let by = $bold(y)$
#let bz = $bold(z)$
#let bA = $bold(A)$
#let bB = $bold(B)$
#let bC = $bold(C)$
#let bD = $bold(D)$
#let bE = $bold(E)$
#let bF = $bold(F)$
#let bG = $bold(G)$
#let bH = $bold(H)$
#let bI = $bold(I)$
#let bJ = $bold(J)$
#let bK = $bold(K)$
#let bL = $bold(L)$
#let bM = $bold(M)$
#let bN = $bold(N)$
#let bP = $bold(P)$
#let bS = $bold(S)$
#let bT = $bold(T)$
#let bU = $bold(U)$
#let bV = $bold(V)$
#let bW = $bold(W)$
#let bX = $bold(X)$
#let bY = $bold(Y)$
#let bZ = $bold(Z)$
#let bxi = $bold(xi)$
#let bpi = $bold(pi)$
#let bth = $bold(theta)$
#let bmu = $bold(mu)$
#let bsi = $bold(sigma)$
#let bga = $bold(gamma)$
// cal letters (only uppercases)
#let cA = $cal(A)$
#let cB = $cal(B)$
#let cC = $cal(C)$
#let cD = $cal(D)$
#let cF = $cal(F)$
#let cG = $cal(G)$
#let cH = $cal(H)$
#let cJ = $cal(J)$
#let cL = $cal(L)$
#let cM = $cal(M)$
#let cN = $cal(N)$
#let cP = $cal(P)$
#let cS = $cal(S)$
#let cV = $cal(V)$
#let cW = $cal(W)$
#let cX = $cal(X)$
// letters with hat
#let ha = $cal(a)$
#let hb = $cal(b)$
#let hc = $cal(c)$
#let hd = $cal(d)$
#let he = $cal(e)$
#let hf = $cal(f)$
#let hg = $cal(g)$
#let hh = $cal(h)$
// #let hi = $cal(i)$
// #let hj = $cal(j)$
// #let hk = $cal(k)$ // used for h_i h_j h_k
#let hm = $cal(m)$
#let hn = $cal(n)$
#let hs = $cal(s)$
#let ht = $cal(t)$
#let hu = $cal(u)$
#let hv = $cal(v)$
#let hw = $cal(w)$
#let hx = $cal(x)$
#let hy = $cal(y)$
#let hz = $cal(z)$
#let hA = $cal(A)$
#let hB = $cal(B)$
#let hC = $cal(C)$
#let hD = $cal(D)$
#let hE = $cal(E)$
#let hF = $cal(F)$
#let hG = $cal(G)$
#let hH = $cal(H)$
#let hI = $cal(I)$
#let hJ = $cal(J)$
#let hK = $cal(K)$
#let hL = $cal(L)$
#let hM = $cal(M)$
#let hN = $cal(N)$
#let hO = $cal(O)$
#let hP = $cal(P)$
#let hQ = $cal(Q)$
#let hS = $cal(S)$
#let hT = $cal(T)$
#let hU = $cal(U)$
#let hV = $cal(V)$
#let hW = $cal(W)$
#let hX = $cal(X)$
#let hY = $cal(Y)$
#let hZ = $cal(Z)$
// letters with tilde
// #let ta = $cal(a)$ // 'ta' used for tau
#let tb = $cal(b)$
#let tc = $cal(c)$
#let td = $cal(d)$
#let te = $cal(e)$
#let tf = $cal(f)$
#let tg = $cal(g)$
// #let th = $cal(h)$ // 'th' used for theta
// #let ti = $cal(i)$
// #let tj = $cal(j)$
// #let tk = $cal(k)$ // used for t_i t_j t_k
#let tm = $cal(m)$
#let tn = $cal(n)$
#let to = $cal(o)$
#let tp = $cal(p)$
#let tq = $cal(q)$
#let ts = $cal(s)$
#let tt = $cal(t)$
#let tu = $cal(u)$
#let tv = $cal(v)$
#let tw = $cal(w)$
#let tx = $cal(x)$
#let ty = $cal(y)$
#let tz = $cal(z)$
#let tA = $cal(A)$
#let tB = $cal(B)$
#let tC = $cal(C)$
#let tD = $cal(D)$
#let tE = $cal(E)$
#let tF = $cal(F)$
#let tG = $cal(G)$
#let tH = $cal(H)$
#let tI = $cal(I)$
#let tJ = $cal(J)$
#let tH = $cal(H)$
#let tI = $cal(I)$
#let tJ = $cal(J)$
#let tK = $cal(K)$
#let tM = $cal(M)$
#let tN = $cal(N)$
#let tO = $cal(O)$
#let tP = $cal(P)$
#let tQ = $cal(Q)$
#let tS = $cal(S)$
#let tT = $cal(T)$
#let tU = $cal(U)$
#let tV = $cal(V)$
#let tW = $cal(W)$
#let tX = $cal(X)$
#let tY = $cal(Y)$
#let tZ = $cal(Z)$
// letters with arrow
#let aa = $cal(a)$
#let ab = $cal(b)$
#let ac = $cal(c)$
#let ad = $cal(d)$
#let ae = $cal(e)$
#let af = $cal(f)$
#let ag = $cal(g)$
#let ah = $cal(h)$
// #let ai = $cal(i)$
// #let aj = $cal(j)$
// #let ak = $cal(k)$ // used for a_i a_j a_k
// #let as = $cal(s)$ // 'as' is a keyword
#let at = $cal(t)$
#let au = $cal(u)$
#let av = $cal(v)$
#let aw = $cal(w)$
#let ax = $cal(x)$
#let ay = $cal(y)$
#let az = $cal(z)$
#let aA = $cal(A)$
#let aB = $cal(B)$
#let aC = $cal(C)$
#let aD = $cal(D)$
#let aE = $cal(E)$
#let aF = $cal(F)$
#let aG = $cal(G)$
#let aH = $cal(H)$
#let aI = $cal(I)$
#let aJ = $cal(J)$
#let aK = $cal(K)$
#let aS = $cal(S)$
#let aT = $cal(T)$
#let aU = $cal(U)$
#let aV = $cal(V)$
#let aW = $cal(W)$
#let aX = $cal(X)$
#let aY = $cal(Y)$
#let aZ = $cal(Z)$
// overline letters
#let oa = $cal(a)$ // or overline (slightly too long I think)
#let ob = $cal(b)$
#let oc = $cal(c)$
#let od = $cal(d)$
#let oe = $cal(e)$
#let of = $cal(f)$
#let og = $cal(g)$
#let oh = $cal(h)$
#let oi = $cal(i)$
#let oj = $cal(j)$
#let ok = $cal(k)$
// #let om = $cal(m)$ // 'om' used for omega
#let on = $cal(n)$
#let os = $cal(s)$
#let ot = $cal(t)$
#let ou = $cal(u)$
#let ov = $cal(v)$
#let ow = $cal(w)$
#let ox = $cal(x)$
#let oy = $cal(y)$
#let oz = $cal(z)$
#let oA = $cal(A)$
#let oB = $cal(B)$
#let oC = $cal(C)$
#let oD = $cal(D)$
#let oE = $cal(E)$
#let oF = $cal(F)$
#let oG = $cal(G)$
#let oH = $cal(H)$
#let oI = $cal(I)$
#let oJ = $cal(J)$
#let oK = $cal(K)$
// #let oM = $cal(M)$ // 'oM' used for cal
#let oN = $cal(N)$
#let oP = $cal(P)$
#let oQ = $cal(Q)$
#let oS = $cal(S)$
#let oT = $cal(T)$
#let oU = $cal(U)$
#let oV = $cal(V)$
#let oW = $cal(W)$
#let oX = $cal(X)$
#let oY = $cal(Y)$
#let oZ = $cal(Z)$

// ---------- subscripts for common letters ----------
#let x0 = $x_0$
#let x1 = $x_1$
#let x2 = $x_2$
// #let xi = $x_i$ // 'xi' used for xi
#let xj = $x_j$
#let xk = $x_k$
#let xm = $x_m$
#let xM = $x_M$
#let xn = $x_n$
#let xN = $x_N$
#let xt = $x_t$
#let xT = $x_T$
#let y0 = $y_0$
#let y1 = $y_1$
#let y2 = $y_2$
#let yi = $y_i$
#let yj = $y_j$
#let yk = $y_k$
#let ym = $y_m$
#let yM = $y_M$
#let yn = $y_n$
#let yN = $y_N$
#let yt = $y_t$
#let yT = $y_T$
#let z0 = $z_0$
#let z1 = $z_1$
#let z2 = $z_2$
#let zi = $z_i$
#let zj = $z_j$
#let zk = $z_k$
#let zm = $z_m$
#let zM = $z_M$
#let zn = $z_n$
#let zN = $z_N$
#let zt = $z_t$
#let zT = $z_T$
#let s0 = $s_0$
#let s1 = $s_1$
#let s2 = $s_2$
// #let si = $s_i$ // 'si' used for sigma
#let sj = $s_j$
#let sk = $s_k$
#let sm = $s_m$
#let sM = $s_M$
#let sn = $s_n$
#let sN = $s_N$
#let t0 = $t_0$
#let t1 = $t_1$
#let t2 = $t_2$
#let ti = $t_i$
#let tj = $t_j$
#let tk = $t_k$
// #let tm = $t_m$
// #let tM = $t_M$
// #let tn = $t_n$
// #let tN = $t_N$ // 't' used for tilde
#let u0 = $u_0$
#let u1 = $u_1$
#let u2 = $u_2$
#let ui = $u_i$
#let uj = $u_j$
#let uk = $u_k$
#let um = $u_m$
#let uM = $u_M$
#let un = $u_n$
#let uN = $u_N$
#let v0 = $v_0$
#let v1 = $v_1$
#let v2 = $v_2$
#let vi = $v_i$
#let vj = $v_j$
#let vk = $v_k$
#let vm = $v_m$
#let vM = $v_M$
#let vn = $v_n$
#let vN = $v_N$
#let w0 = $w_0$
#let w1 = $w_1$
#let w2 = $w_2$
#let wi = $w_i$
#let wj = $w_j$
#let wk = $w_k$
#let wm = $w_m$
#let wM = $w_M$
#let wn = $w_n$
#let wN = $w_N$
#let a0 = $a_0$
#let a1 = $a_1$
#let a2 = $a_2$
#let ai = $a_i$
#let aj = $a_j$
#let ak = $a_k$
#let am = $a_m$
#let aM = $a_M$
#let an = $a_n$
#let aN = $a_N$
#let b0 = $b_0$
#let b1 = $b_1$
#let b2 = $b_2$
#let bi = $b_i$
#let bj = $b_j$
#let bk = $b_k$
// #let bm = $b_m$
// #let bM = $b_M$
// #let bn = $b_n$
// #let bN = $b_N$ // 'b' used for bold
#let c0 = $c_0$
#let c1 = $c_1$
#let c2 = $c_2$
#let ci = $c_i$
#let cj = $c_j$
#let ck = $c_k$
// #let cm = $c_m$ // 'cm' used as a unit
// #let cM = $c_M$ // 'cM' used for cal
#let cn = $c_n$
// #let cN = $c_N$ // 'cN' used for cal
#let d0 = $d_0$
#let d1 = $d_1$
#let d2 = $d_2$
#let di = $d_i$
#let dj = $d_j$
#let dk = $d_k$
#let dm = $d_m$
#let dM = $d_M$
#let dn = $d_n$
#let dN = $d_N$
#let e0 = $e_0$
#let e1 = $e_1$
#let e2 = $e_2$
#let ei = $e_i$
#let ej = $e_j$
#let ek = $e_k$
#let em = $e_m$
#let eM = $e_M$
#let en = $e_n$
#let eN = $e_N$
#let f0 = $f_0$
#let f1 = $f_1$
#let f2 = $f_2$
#let fi = $f_i$
#let fj = $f_j$
#let fk = $f_k$
#let fm = $f_m$
#let fM = $f_M$
#let fn = $f_n$
#let fN = $f_N$
#let g0 = $g_0$
#let g1 = $g_1$
#let g2 = $g_2$
#let gi = $g_i$
#let gj = $g_j$
#let gk = $g_k$
#let gm = $g_m$
#let gM = $g_M$
#let gn = $g_n$
#let gN = $g_N$
#let h0 = $h_0$
#let h1 = $h_1$
#let h2 = $h_2$
#let hi = $h_i$
#let hj = $h_j$
#let hk = $h_k$
// #let hm = $h_m$
// #let hM = $h_M$
// #let hn = $h_n$
// #let hN = $h_N$ // 'h' used for hat
#let i0 = $i_0$
#let i1 = $i_1$
#let i2 = $i_2$
// #let ii = $i_i$ 'ii' used for i i with backspace between
// #let ij = $i_j$ 'ij' used for i j with backspace between
// #let ik = $i_k$ // 'ik' used for i k with backspace between
#let im = $i_m$
#let iM = $i_M$
// #let in = $i_n$ // 'in' is a keyword
#let iN = $i_N$
#let j0 = $j_0$
#let j1 = $j_1$
#let j2 = $j_2$
// #let ji = $j_i$ // 'ji' used for j i with backspace between
// #let jj = $j_j$ // 'jj' used for j j with backspace between
// #let jk = $j_k$ // 'jk' used for j k with backspace between
#let jm = $j_m$
#let jM = $j_M$
#let jn = $j_n$
#let jN = $j_N$
#let k0 = $k_0$
#let k1 = $k_1$
#let k2 = $k_2$
// #let ki = $k_i$ // 'ki' used for k i with backspace between
// #let kj = $k_j$ // 'kj' used for k j with backspace between
// #let kk = $k_k$ // 'kk' used for k k with backspace between
#let km = $k_m$
#let kM = $k_M$
#let kn = $k_n$
#let kN = $k_N$
