[package]
name = "admonition"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["crd233"]
license = "MIT"
repository = "https://github.com/lf-/typst-algorithmic"
exclude = ["*.pdf"]
description = "Admonitions for Typst"